window.LUZ_CONTENT = {
  site: { title:'Lüz Frequencies — Lüz', description:'Lüz — Music Production, Sound Design & Audio Engineering.', year:'2026', established:['20','20','26'], specs:['48KHZ','24BIT','STEREO'] },
  hero: { name:'LÜZ', discipline:'MUSIC PRODUCTION / SOUND DESIGN / AUDIO ENGINEERING', image:'assets/IMG_4118.jpg', imageAlt:'Lüz portrait by the waterfront', tags:['VISUALS','SOUND','EMOTION','FREQUENCY'], counter:'01 / 01', showreel:{label:'PLAY SIREN',duration:'03:05',audio:'assets/Siren-Instrumental-Final-25mb.mp3'} },
  projects:[
    {number:'01',title:'I F E S D',thumbLabel:'I FEEL EVERYTHING SO DEEPLY DEMO',thumbClass:'blue',thumbImage:'',description:'MUSIC PRODUCTION, AUDIO CLEANING MIXING AND MASTERING',year:'2026',audio:'',video:'assets/Ifeeleverythingsodeeply-v2.m4v',link:'',details:'An original song demo exploring the intersection between electronic production, R&B-inspired rhythms, and melancholic Portuguese vocals. The track is an introspective exploration of what it means to experience emotions with overwhelming intensity, often without a clear reason or explanation, and the challenge of carrying that weight on a daily basis. Through layered electronic textures, restrained R&B grooves, and an emotionally vulnerable vocal performance in Portuguese, the production reflects the contrast between an intimate inner world and the impact it can have on the people and relationships around us. The result is a deeply personal piece that explores emotional intensity, vulnerability, and the struggle of learning to live with feelings that cannot always be controlled or understood.'},
    {number:'02',title:'FASHION FILM',thumbLabel:'FASHION FILM',thumbClass:'red-image',thumbImage:'',description:'SOUND DESIGN, MUSIC PRODUCTION',year:'2024',audio:'',video:'assets/FashionFilmDemo-25mb.mp4',link:'',details:'A sound design project created for a fashion film exploring disruptive art, emotional expression, and the freedom to create without restraint. Rather than relying on conventional sound libraries, the entire soundscape was built from the sounds produced by the performer throughout the film — from the movement of fabric and jewelry to the texture and impact of paint as she interacted with it. These raw recordings were manipulated, layered, and transformed to create an immersive soundscape that mirrors the film’s chaotic and expressive visual language. The concept reflects the idea that, sometimes, we need to let noise, emotion, and instinct take over in order to create something truly authentic.'},
    {number:'03',title:'US - JORDAN PEELE',thumbLabel:'US - JORDAN PEELE',thumbClass:'blue-dark',thumbImage:'',description:'SOUND DESIGN RECREATION, FOLEY',year:'2023',audio:'',video:'assets/Ferreira_Cassandra-SupportiveVersion-25mb.mp4',link:'',details:'A recreation of the sound design for one of the most iconic scenes from Jordan Peele’s "Us", created entirely through practical Foley, vocal performance, and sound manipulation. The soundscape was built from everyday objects and unconventional materials, including handcuffs, scissors, kitchen knives, fabric, and various other objects, carefully recorded and transformed to recreate the physicality and tension of the original scene. Drawing on my background in theatre and performance, I also recreated the characters’ screams, breathing, and expressions of pain and distress, using vocal performance as an essential part of the sound design. The project explores how ordinary objects and human performance can be transformed into unsettling cinematic sounds, recreating the tension, brutality, and emotional intensity of the original scene without relying on pre-existing sound effects.'},
    {number:'04',title:'N0 L4B3L',thumbLabel:'N0 L4B3L PROJECT',thumbClass:'red-dark',thumbImage:'',description:'MUSIC PRODUCTION, MIXING AND MASTERING',year:'2024',audio:'',video:'assets/NOLABELPROJECT-25MB.mp4',link:'',details:'N0 L4b3l: Music Without Identity - A revolutionary project created by game designer Pedro Ferreira in collaboration with sound engineer and producer Lüz, N0 L4b3l aims to make audiences experience music in an entirely different way. Built around anonymity, N0 L4b3l removes the identity behind the artist — no face, ethnicity, gender, genre, or predefined theme — allowing the music to exist purely as art, free from the expectations and influences associated with its creator. The project follows Pedro and Lüz’s first collaboration earlier this year, on Pedro’s most acclaimed game to date: a narrative experience based on a true story set during the Second World War. Lüz composed and produced the game’s sound design, contributing to what would become one of the standout games participating in this year’s PlayStation Awards. As Pedro explains: “Every day, even if we don’t want to, we are influenced by what we see, hear, and even touch.” With N0 L4b3l, the duo seeks to challenge that influence and unleash the purest form of art.'}
  ],
  about:{title:'ABOUT',paragraphs:["I’m Lüz, a music producer, sound designer and audio engineer with a passion for creating immersive sonic experiences. I work across multiple disciplines, from music production and mixing to post-production for visual media.",'My work blends technical precision with artistic instinct to craft sound that connects and transforms.'],cv:''},
  sound:{title:'SOUND',services:['MUSIC PRODUCTION','SOUND DESIGN','FOLEY','MIXING & MASTERING']},
  contact:{title:'CONTACT',email:'luzfrequencies@gmail.com',phone:'+351 926 654 757',instagram:'@_heyimkassandra',instagramUrl:'https://www.instagram.com/_heyimkassandra/',location:'Based in Lisbon, Portugal',cta:'LET’S CREATE SOMETHING REAL.'},
  footer:{copyright:'LÜZ FREQUENCIES © 2026',nowPlaying:'NOW PLAYING — N0L4B3L —',duration:'01:02'},
  translations:{
    en:{work:'SELECTED WORK',sound:'SOUND',about:'ABOUT',contact:'CONTACT',playShowreel:'PLAY SIREN',pause:'PAUSE',playProject:'PLAY PROJECT',viewAll:'VIEW ALL PROJECTS',downloadCv:'DOWNLOAD CV',browseSounds:'BROWSE ALL SOUNDS',close:'CLOSE',noAudio:'Audio not added yet.',openProject:'OPEN PROJECT',editing:'EDIT EVERYTHING',editHint:'You can edit the site content, links, images and audio paths here. Save for a preview, or export content.js when you are ready to publish.',export:'EXPORT CONTENT FILE',reset:'RESET PREVIEW',save:'SAVE CHANGES'},
    pt:{work:'TRABALHO SELECIONADO',sound:'SOM',about:'SOBRE',contact:'CONTACTO',playShowreel:'OUVIR SHOWREEL',pause:'PAUSA',playProject:'OUVIR PROJETO',viewAll:'VER TODOS OS PROJETOS',downloadCv:'DESCARREGAR CV',browseSounds:'VER TODOS OS SONS',close:'FECHAR',noAudio:'O áudio ainda não foi adicionado.',openProject:'ABRIR PROJETO',editing:'EDITAR TUDO',editHint:'Podes editar aqui o conteúdo, links, imagens e caminhos de áudio. Guarda para pré-visualizar ou exporta o content.js quando estiveres pronta para publicar.',export:'EXPORTAR CONTENT.JS',reset:'REPOR V5',save:'GUARDAR ALTERAÇÕES'}
  }
};
